spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName=: 'org.h2.Driver'
    username: 'sa'
    password: 'sa'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
  h2:
    console:
      enabled: true

app:
  security:
    expiration: 43200000
  testing:
    uri: 'http://localhost:8080'
    user: 'prueba'
    password: 'prueba123'
